name: Next.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Ensure ESLint is installed
        run: npm install eslint eslint-config-next --save-dev --legacy-peer-deps

      - name: Build project
        run: npm run build

      - name: Run lint (non-blocking)
        run: npm run lint -- --fix || echo "Lint warnings ignored"
